export type BackendIntegrationStatus =
  | 'connected'
  | 'hidden'
  | 'disconnected'
  | 'missing';

export interface BackendIntegrationInventoryEntry {
  endpoint: string;
  frontend: string;
  component: string;
  route: string;
  status: BackendIntegrationStatus;
  plan: string;
}

export const BACKEND_INTEGRATION_INVENTORY = [
  {
    endpoint: '/api/status',
    frontend: 'useGreenhouse, useSimulationRuntimeControls',
    component: 'SimulationRuntimePanel, Overview runtime chip',
    route: 'Overview > Command, Live Climate',
    status: 'connected',
    plan: 'Keep compact runtime state in Overview and full controls in Live Climate.',
  },
  {
    endpoint: '/api/start',
    frontend: 'useGreenhouse, useSimulationRuntimeControls',
    component: 'SimulationRuntimePanel',
    route: 'Live Climate',
    status: 'connected',
    plan: 'Keep runtime action buttons out of Overview detail density.',
  },
  {
    endpoint: '/api/step',
    frontend: 'useSimulationRuntimeControls',
    component: 'SimulationRuntimePanel',
    route: 'Live Climate',
    status: 'connected',
    plan: 'Preserve manual stepping in the dedicated climate/control route.',
  },
  {
    endpoint: '/api/run',
    frontend: 'useSimulationRuntimeControls',
    component: 'SimulationRuntimePanel',
    route: 'Live Climate',
    status: 'connected',
    plan: 'Preserve batch runtime execution in the dedicated climate/control route.',
  },
  {
    endpoint: '/api/pause',
    frontend: 'useSimulationRuntimeControls',
    component: 'SimulationRuntimePanel',
    route: 'Live Climate',
    status: 'connected',
    plan: 'Preserve pause action with degraded/error feedback in the runtime panel.',
  },
  {
    endpoint: '/api/resume',
    frontend: 'useSimulationRuntimeControls',
    component: 'SimulationRuntimePanel',
    route: 'Live Climate',
    status: 'connected',
    plan: 'Preserve resume action with runtime status refresh.',
  },
  {
    endpoint: '/api/stop',
    frontend: 'useSimulationRuntimeControls',
    component: 'SimulationRuntimePanel',
    route: 'Live Climate',
    status: 'connected',
    plan: 'Preserve stop action with runtime status refresh.',
  },
  {
    endpoint: '/api/speed',
    frontend: 'useSimulationRuntimeControls',
    component: 'SimulationRuntimePanel',
    route: 'Live Climate',
    status: 'connected',
    plan: 'Preserve speed setting as a dedicated runtime control.',
  },
  {
    endpoint: '/ws/sim/{crop}',
    frontend: 'useGreenhouse',
    component: 'Live telemetry surfaces, charts, Overview metrics',
    route: 'Overview, Live Climate, Model Lab',
    status: 'connected',
    plan: 'Use WS_URL and preserve crop-scoped telemetry state.',
  },
  {
    endpoint: '/ws/forecast/{crop}',
    frontend: 'useGreenhouse',
    component: 'ForecastPanel, assistant context, advisor context',
    route: 'Model Lab, Advisor & Work',
    status: 'connected',
    plan: 'Use FORECAST_WS_URL for live snapshots and keep REST polling as fallback.',
  },
  {
    endpoint: '/api/forecast/{crop}',
    frontend: 'useGreenhouse',
    component: 'ForecastPanel, assistant context, advisor context',
    route: 'Model Lab, Advisor & Work',
    status: 'connected',
    plan: 'Keep REST polling as forecast fallback and cold-start hydrator.',
  },
  {
    endpoint: '/api/config/ops',
    frontend: 'useGreenhouse, ControlPanel',
    component: 'ControlPanel',
    route: 'Live Climate',
    status: 'connected',
    plan: 'Keep ops settings crop-scoped and editable in the climate/control route.',
  },
  {
    endpoint: '/api/config/crop',
    frontend: 'useSimulationRuntimeControls',
    component: 'SimulationRuntimePanel',
    route: 'Live Climate',
    status: 'connected',
    plan: 'Expose crop runtime config through the full controls surface.',
  },
  {
    endpoint: '/api/settings',
    frontend: 'SettingsRoutePage, useGreenhouse',
    component: 'SettingsRoutePage',
    route: 'Settings',
    status: 'connected',
    plan: 'Keep GET/POST settings on the dedicated Settings route.',
  },
  {
    endpoint: '/api/feedback',
    frontend: 'ControlPanel, recommendation actions',
    component: 'ControlPanel, action feedback controls',
    route: 'Live Climate, Advisor & Work',
    status: 'connected',
    plan: 'Keep feedback controls near recommendation/action surfaces.',
  },
  {
    endpoint: '/api/rtr/profiles',
    frontend: 'useRtrProfiles',
    component: 'RTROptimizerPanel, RtrRoutePage',
    route: 'RTR Optimizer',
    status: 'connected',
    plan: 'Expose RTR as a first-class navigation item.',
  },
  {
    endpoint: '/api/rtr/state',
    frontend: 'useRtrOptimizer',
    component: 'RTROptimizerPanel',
    route: 'RTR Optimizer',
    status: 'connected',
    plan: 'Keep live RTR state in the dedicated optimizer route.',
  },
  {
    endpoint: '/api/rtr/optimize',
    frontend: 'useRtrOptimizer',
    component: 'RTROptimizerPanel, ScenarioOptimizerPreview',
    route: 'Overview > Command, RTR Optimizer',
    status: 'connected',
    plan: 'Show only summary recommendation in Overview and full result in RTR.',
  },
  {
    endpoint: '/api/rtr/scenario',
    frontend: 'useRtrOptimizer',
    component: 'RTROptimizerPanel',
    route: 'RTR Optimizer, Scenario Lab',
    status: 'connected',
    plan: 'Keep scenario comparisons in RTR and expose the same full surface in Scenario Lab.',
  },
  {
    endpoint: '/api/rtr/sensitivity',
    frontend: 'useRtrOptimizer',
    component: 'RTROptimizerPanel',
    route: 'RTR Optimizer, Scenario Lab',
    status: 'connected',
    plan: 'Keep sensitivity controls in RTR and Scenario Lab rather than Overview density.',
  },
  {
    endpoint: '/api/rtr/area-settings',
    frontend: 'useRtrOptimizer, AreaUnitContext',
    component: 'RTROptimizerPanel',
    route: 'RTR Optimizer',
    status: 'connected',
    plan: 'Preserve actual-area projection through the shared area-unit context.',
  },
  {
    endpoint: '/api/models/snapshot',
    frontend: 'useModelRuntimeWorkbench',
    component: 'ModelRuntimeBridge',
    route: 'Overview > Dashboard, Model Lab',
    status: 'connected',
    plan: 'Keep compact bridge in Overview and full workbench in Model Lab/Crop Work.',
  },
  {
    endpoint: '/api/models/replay',
    frontend: 'useModelRuntimeWorkbench',
    component: 'ModelRuntimeBridge',
    route: 'Model Lab',
    status: 'connected',
    plan: 'Expose replay in the model lab surface.',
  },
  {
    endpoint: '/api/models/scenario',
    frontend: 'useModelRuntimeWorkbench',
    component: 'ModelRuntimeBridge, ModelScenarioWorkbench',
    route: 'Model Lab, Scenario Lab',
    status: 'connected',
    plan: 'Expose crop-state scenario runs in Model Lab and full process-model What-if controls in Scenario Lab.',
  },
  {
    endpoint: '/api/models/sensitivity',
    frontend: 'useModelRuntimeWorkbench',
    component: 'ModelRuntimeBridge, ModelScenarioWorkbench',
    route: 'Model Lab, Scenario Lab',
    status: 'connected',
    plan: 'Expose model sensitivity in Model Lab and control partial derivatives in Scenario Lab.',
  },
  {
    endpoint: '/api/advisor/summary',
    frontend: 'useSmartGrowAdvisor',
    component: 'TodayActionBoard, AdvisorTabs',
    route: 'Overview > Command, Advisor & Work',
    status: 'connected',
    plan: 'Show 3-4 highest-priority actions in Overview and full detail in Advisor.',
  },
  {
    endpoint: '/api/advisor/tab/{tab_name}',
    frontend: 'useSmartGrowAdvisor, AdvisorTabs',
    component: 'AdvisorTabs',
    route: 'Advisor & Work, Knowledge & Agronomy',
    status: 'connected',
    plan: 'Keep tab delegate as the primary advisor surface while preserving direct endpoint compatibility.',
  },
  {
    endpoint: '/api/advisor/chat',
    frontend: 'useAiAssistant',
    component: 'ChatAssistant, AssistantDrawer',
    route: 'Assistant',
    status: 'connected',
    plan: 'Expose advisor chat in Assistant and compact CTA in Overview.',
  },
  {
    endpoint: '/api/advisor/environment',
    frontend: 'AdvisorTabs via direct compatibility path',
    component: 'Environment advisor tab',
    route: 'Advisor & Work',
    status: 'connected',
    plan: 'Document as direct compatibility surface; primary UI can still use /advisor/tab/environment.',
  },
  {
    endpoint: '/api/advisor/physiology',
    frontend: 'AdvisorTabs via direct compatibility path',
    component: 'Physiology advisor tab',
    route: 'Advisor & Work',
    status: 'connected',
    plan: 'Document as direct compatibility surface; primary UI can still use /advisor/tab/physiology.',
  },
  {
    endpoint: '/api/advisor/work-tradeoff',
    frontend: 'AdvisorTabs via direct compatibility path',
    component: 'Work tradeoff tab',
    route: 'Advisor & Work',
    status: 'connected',
    plan: 'Document as direct compatibility surface; primary UI can still use the tab delegate.',
  },
  {
    endpoint: '/api/advisor/harvest',
    frontend: 'AdvisorTabs via direct compatibility path',
    component: 'Harvest advisor tab',
    route: 'Advisor & Work',
    status: 'connected',
    plan: 'Document as direct compatibility surface; primary UI can still use the tab delegate.',
  },
  {
    endpoint: '/api/environment/recommend',
    frontend: 'useSmartGrowAdvisor',
    component: 'AdvisorTabs, TodayActionBoard',
    route: 'Overview > Command, Advisor & Work',
    status: 'connected',
    plan: 'Keep environment actions as Overview summaries and detailed advisor cards.',
  },
  {
    endpoint: '/api/work/recommend',
    frontend: 'useSmartGrowAdvisor',
    component: 'AdvisorTabs, TodayActionBoard',
    route: 'Overview > Command, Advisor & Work',
    status: 'connected',
    plan: 'Keep work actions as Overview summaries and detailed advisor cards.',
  },
  {
    endpoint: '/api/knowledge/status',
    frontend: 'useSmartGrowKnowledge',
    component: 'SmartGrowSurfacePanel, top readiness badge',
    route: 'Knowledge & Agronomy, Overview > Command',
    status: 'connected',
    plan: 'Keep readiness badge compact in Overview and full DB status in Resources/Assistant.',
  },
  {
    endpoint: '/api/knowledge/reindex',
    frontend: 'useModelRuntimeWorkbench, SmartGrowSurfacePanel',
    component: 'SmartGrowSurfacePanel',
    route: 'Knowledge & Agronomy',
    status: 'connected',
    plan: 'Expose reindex as a knowledge maintenance action.',
  },
  {
    endpoint: '/api/knowledge/query',
    frontend: 'useSmartGrowKnowledge, AskSearchPage',
    component: 'AskSearchPage',
    route: 'Assistant, Knowledge & Agronomy',
    status: 'connected',
    plan: 'Keep query/search in Assistant while preserving resource entry cards.',
  },
  {
    endpoint: '/api/pesticides/recommend',
    frontend: 'useSmartGrowAdvisor',
    component: 'AdvisorTabs pesticide surface',
    route: 'Knowledge & Agronomy, Alerts',
    status: 'connected',
    plan: 'Expose pesticide rotation and manual-review flags in agronomy/safety surfaces.',
  },
  {
    endpoint: '/api/nutrients/recommend',
    frontend: 'useSmartGrowAdvisor',
    component: 'AdvisorTabs nutrient surface',
    route: 'Knowledge & Agronomy, Resources',
    status: 'connected',
    plan: 'Expose nutrient recommendations in Resources and agronomy detail.',
  },
  {
    endpoint: '/api/nutrients/correction',
    frontend: 'useSmartGrowAdvisor',
    component: 'AdvisorTabs nutrient correction surface',
    route: 'Knowledge & Agronomy, Resources',
    status: 'connected',
    plan: 'Expose correction draft, blocked, and provisional states.',
  },
  {
    endpoint: '/api/weather/daegu',
    frontend: 'useWeatherOutlook',
    component: 'WeatherTrendPanel, WeatherOutlookPanel, WeatherMarketKnowledgeBridge',
    route: 'Overview > Command, Weather & Market',
    status: 'connected',
    plan: 'Show compact bridge in Overview and full weather trend/detail graphs in Trend.',
  },
  {
    endpoint: '/api/market/produce',
    frontend: 'useProducePrices',
    component: 'ProducePricesPanel, WeatherMarketKnowledgeBridge',
    route: 'Overview > Command, Weather & Market',
    status: 'connected',
    plan: 'Show compact market bridge in Overview and KAMIS detail in Trend/Resources.',
  },
  {
    endpoint: '/api/ai/consult',
    frontend: 'useAiCompatibility',
    component: 'AiCompatibilityPanel',
    route: 'Assistant',
    status: 'connected',
    plan: 'Keep compatibility API visible in Assistant with degraded/unavailable states.',
  },
  {
    endpoint: '/api/ai/chat',
    frontend: 'useAiCompatibility',
    component: 'AiCompatibilityPanel',
    route: 'Assistant',
    status: 'connected',
    plan: 'Keep compatibility chat API visible in Assistant with degraded/unavailable states.',
  },
] as const satisfies readonly BackendIntegrationInventoryEntry[];

export const REQUIRED_BACKEND_ENDPOINTS = [
  '/api/status',
  '/api/start',
  '/api/step',
  '/api/run',
  '/api/pause',
  '/api/resume',
  '/api/stop',
  '/api/speed',
  '/ws/sim/{crop}',
  '/ws/forecast/{crop}',
  '/api/config/ops',
  '/api/config/crop',
  '/api/settings',
  '/api/feedback',
  '/api/rtr/profiles',
  '/api/rtr/state',
  '/api/rtr/optimize',
  '/api/rtr/scenario',
  '/api/rtr/sensitivity',
  '/api/rtr/area-settings',
  '/api/models/snapshot',
  '/api/models/replay',
  '/api/models/scenario',
  '/api/models/sensitivity',
  '/api/advisor/summary',
  '/api/advisor/tab/{tab_name}',
  '/api/advisor/chat',
  '/api/advisor/environment',
  '/api/advisor/physiology',
  '/api/advisor/work-tradeoff',
  '/api/advisor/harvest',
  '/api/environment/recommend',
  '/api/work/recommend',
  '/api/knowledge/status',
  '/api/knowledge/reindex',
  '/api/knowledge/query',
  '/api/pesticides/recommend',
  '/api/nutrients/recommend',
  '/api/nutrients/correction',
  '/api/weather/daegu',
  '/api/market/produce',
  '/api/ai/consult',
  '/api/ai/chat',
] as const;
