export const phytoSyncCopyKo = {
  brand: 'PhytoSync',
  workspaces: '워크스페이스',
  overview: '오늘 개요',
  control: '온실 환경',
  growth: '생육·작업',
  nutrient: '양액·관수',
  protection: '방제',
  harvest: '수확·출하',
  resources: '자재·비용',
  alerts: '긴급 알림',
  ask: '질문하기',
  search: '자료 찾기',
  evidence: '참고 메모',
  reviewState: '반영 상태',
} as const;
